version: "3.9"
name: "akari-staging"

services:
  postgres:
    container_name: Akari-Postgres
    image: postgres:15
    env_file:
      - .env
    volumes:
      - staging_postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432


  redis:
    container_name: Akari-Redis
    image: redis/redis-stack:7.0.6-RC5
    ports:
      - 6379:6379
    volumes:
      - staging_redis_stack_volume:/data
    command: redis-stack-server --protected-mode no

  akari:
    container_name: Akari
    image: no767/akari:edge
    command: sh -c '/Akari/wait-for postgres:5432 -- echo "[Wait-for] PostgreSQL is fully up. Waiting for Redis" && /Akari/wait-for redis:6379 -- echo "[Wait-for] Redis is fully up. Starting Akari" && /Akari/start.sh'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  staging_postgres_volume:
  staging_redis_stack_volume:
