version: "3.9"
services:
  postgres:
    container_name: Akari-Postgres-Dev
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: Akari-Redis-Dev
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    command: redis-server --save 60 1 --loglevel warning

  akari:
    container_name: Akari-Dev
    build: 
      context: .
      dockerfile: ./Debian-Docker/Dockerfile
    command: sh -c '/Akari/wait-for postgres:5432 -- echo "[Wait-for] PostgreSQL is fully up. Starting Akari" && /Akari/start.sh'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_volume:
  redis_volume: