[tool.poetry]
name = "akari"
version = "0.1.0"
description = "A general-purpose toolkit bot for servers"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.21.0"
aiodns = "^3.0.0"
Brotli = "^1.0.9"
orjson = "^3.8.0"
uvloop = "^0.17.0"
cchardet = "^2.1.7"
asyncpg = "^0.26.0"
tortoise-orm = {extras = ["accel"], version = "^0.19.2"}
py-cord = "^2.1.3"
rin-exceptions = "^1.0.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[tool.isort]
profile = 'black'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
