[tool.poetry]
name = "Akari"
version = "1.0.0"
description = "A utliity toolkit bot for Discord support servers"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
python-dotenv = "^0.21.0"
aiodns = "^3.0.0"
Brotli = "^1.0.9"
uvloop = "^0.17.0"
rin-exceptions = "^1.0.3"
pysimdjson = "^5.0.2"
pytimeparse = "^1.1.8"
orjson = "^3.8.3"
ormsgpack = "^1.2.4"
discord-py = {extras = ["voice"], version = "^2.1.0"}
ciso8601 = "^2.3.0"
prisma = "^0.8.0"
redis = {extras = ["hiredis"], version = "^4.4.2"}
aiocache = "^0.12.0"
rich = "^13.3.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
pyinstrument = "^4.3.0"
pyright = "^1.1.291"


[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-asyncio = "^0.20.3"
nox = "^2022.11.21"
nox-poetry = "^1.0.2"


[tool.poetry.group.types.dependencies]
types-redis = "^4.4.0.3"

[tool.isort]
profile = 'black'

[tool.pyright]
include = ["Bot/**"]
exclude = ["**/__pycache__", "**/.mypy_cache", "**/.dmpypy.json"]
ignore = ["Docker"]
reportMissingImports = true
reportMissingTypeStubs = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
