[tool.poetry]
name = "akari"
version = "0.2.0"
description = "A general-purpose toolkit bot for servers"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
python-dotenv = "^0.21.0"
aiodns = "^3.0.0"
Brotli = "^1.0.9"
orjson = "^3.8.0"
uvloop = "^0.17.0"
asyncpg = "^0.27.0"
tortoise-orm = {extras = ["accel"], version = "^0.19.2"}
rin-exceptions = "^1.0.3"
py-cord = "2.3.2"
pysimdjson = "^5.0.2"
charset-normalizer = "^2.1.1"
coredis = "~4.10.0"
python-dateutil = "^2.8.2"
pytimeparse = "^1.1.8"
python-rapidjson = "^1.9"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
pyinstrument = "^4.3.0"

[tool.isort]
profile = 'black'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
