#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE $POSTGRES_TAGS_DB;
    ALTER DATABASE $POSTGRES_TAGS_DB OWNER TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_TAGS_DB" TO "$POSTGRES_USER";
EOSQL