#!/usr/bin/env bash


AKARI_FIRST_START_CHECK="AKARI_FIRST_START"

if [ ! -f $AKARI_FIRST_START_CHECK ]; then
    touch $AKARI_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN AKARI USING DOCKER!' >> $AKARI_FIRST_START_CHECK
    python3 /Akari/migration-runner.py
fi

exec python3 /Akari/Bot/akaribot.py
