#!/usr/bin/env bash

if [[ -v AKARI_TOKEN ]]; then
    echo "AKARI_TOKEN=${AKARI_TOKEN}" >> /Akari/Bot/.env
else
    echo "Missing Akari's bot token! AKARI_TOKEN environment variable is not set."
    exit 1;
fi

if [[ -v AKARI_DEV_TOKEN ]]; then
    echo "AKARI_DEV_TOKEN=${AKARI_DEV_TOKEN}" >> /Akari/Bot/.env
fi 

if [[ -v POSTGRES_USER ]]; then
    echo "POSTGRES_USER=${POSTGRES_USER}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_USER env var! POSTGRES_USER environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PASSWORD ]]; then
    echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_PASSWORD env var! POSTGRES_PASSWORD environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_HOST ]]; then
    echo "POSTGRES_HOST=${POSTGRES_HOST}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_HOST env var! POSTGRES_HOST environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PORT ]]; then
    echo "POSTGRES_PORT=${POSTGRES_PORT}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_PORT env var! POSTGRES_PORT environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_DB ]]; then
    echo "POSTGRES_DB=${POSTGRES_DB}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_DB env var! POSTGRES_DB environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_DATABASE_URL ]]; then
    echo "POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}" >> /Akari/Bot/Libs/models/.env
else
    echo "Missing POSTGRES_DATABASE_URL env var! POSTGRES_DATABASE_URL environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_HOST ]]; then
    echo "REDIS_HOST=${REDIS_HOST}" >> /Akari/Bot/.env
else
    echo "Missing REDIS_HOST env var! REDIS_HOST environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_PORT ]]; then
    echo "REDIS_PORT=${REDIS_PORT}" >> /Akari/Bot/.env
else
    echo "Missing REDIS_PORT env var! REDIS_PORT environment variable is not set."
    exit 1;
fi

AKARI_FIRST_START_CHECK="AKARI_FIRST_START"

if [ ! -f $AKARI_FIRST_START_CHECK ]; then
    touch $AKARI_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN AKARI USING DOCKER!' >> $AKARI_FIRST_START_CHECK
    prisma db push --schema /Akari/Bot/Libs/models/schema.prisma
fi

exec python3 /Akari/Bot/akaribot.py