#!/usr/bin/env bash

# if [[ -v AKARI_TOKEN ]]; then
#     echo "AKARI_TOKEN=${AKARI_TOKEN}" >> /Akari/Bot/.env
# else
#     echo "Missing Akari's bot token! AKARI_TOKEN environment variable is not set."
#     exit 1;
# fi
#
# if [[ -v AKARI_DEV_TOKEN ]]; then
#     echo "AKARI_DEV_TOKEN=${AKARI_DEV_TOKEN}" >> /Akari/Bot/.env
# fi 
#
# if [[ -v IPC_SECRET_KEY ]]; then
#     echo "IPC_SECRET_KEY=${IPC_SECRET_KEY}" >> /Akari/.env
# else
#     echo "Missing IPC_SECRET_KEY env var! IPC_SECRET_KEY environment variable is not set."
#     exit 1;
# fi
#
# if [[ -v IPC_HOST ]]; then
#     echo "IPC_HOST=${IPC_HOST}" >> /Akari/.env
# else
#     echo "Missing IPC_HOST env var! IPC_HOST environment variable is not set."
#     exit 1;
# fi
#
# if [[ -v DATABASE_URL ]]; then
#     echo "DATABASE_URL=${DATABASE_URL}" >> /Akari/.env
# else
#     echo "Missing DATABASE_URL env var! DATABASE_URL environment variable is not set."
#     exit 1;
# fi
#
# if [[ -v REDIS_HOST ]]; then
#     echo "REDIS_HOST=${REDIS_HOST}" >> /Akari/Bot/.env
# else
#     echo "Missing REDIS_HOST env var! REDIS_HOST environment variable is not set."
#     exit 1;
# fi
#
# if [[ -v REDIS_PORT ]]; then
#     echo "REDIS_PORT=${REDIS_PORT}" >> /Akari/Bot/.env
# else
#     echo "Missing REDIS_PORT env var! REDIS_PORT environment variable is not set."
#     exit 1;
# fi

AKARI_FIRST_START_CHECK="AKARI_FIRST_START"

if [ ! -f $AKARI_FIRST_START_CHECK ]; then
    touch $AKARI_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN AKARI USING DOCKER!' >> $AKARI_FIRST_START_CHECK
    cd /Akari/Bot
    apgmx migrate all 
fi

exec python3 /Akari/Bot/akaribot.py
