#!/usr/bin/env bash

if [[ -v AKARI_TOKEN ]]; then
    echo "Akari_Token=${AKARI_TOKEN}" >> /Akari/Bot/.env
else
    echo "Missing Akari's bot token! AKARI_TOKEN environment variable is not set."
    exit 1;
fi

if [[ -v AKARI_DEV_TOKEN ]]; then
    echo "Akari_Dev_Token=${AKARI_DEV_TOKEN}" >> /Akari/Bot/.env
fi 

if [[ -v POSTGRES_USER ]]; then
    echo "Postgres_User=${POSTGRES_USER}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_USER env var! POSTGRES_USER environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PASSWORD ]]; then
    echo "Postgres_Password=${POSTGRES_PASSWORD}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_PASSWORD env var! POSTGRES_PASSWORD environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_HOST ]]; then
    echo "Postgres_Host=${POSTGRES_HOST}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_HOST env var! POSTGRES_HOST environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PORT ]]; then
    echo "Postgres_Port=${POSTGRES_PORT}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_PORT env var! POSTGRES_PORT environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_DB ]]; then
    echo "Postgres_Akari_DB=${POSTGRES_DB}" >> /Akari/Bot/.env
else
    echo "Missing POSTGRES_DB env var! POSTGRES_DB environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_HOST ]]; then
    echo "Redis_Host=${REDIS_HOST}" >> /Akari/Bot/.env
else
    echo "Missing REDIS_HOST env var! REDIS_HOST environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_PORT ]]; then
    echo "Redis_Port=${REDIS_PORT}" >> /Akari/Bot/.env
else
    echo "Missing REDIS_PORT env var! REDIS_PORT environment variable is not set."
    exit 1;
fi


AKARI_FIRST_START_CHECK="AKARI_FIRST_START"

if [ ! -f $AKARI_FIRST_START_CHECK ]; then
    touch $AKARI_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN AKARI USING DOCKER!' >> $AKARI_FIRST_START_CHECK
    python3 /Akari/seeder.py
fi

exec python3 /Akari/Bot/akari.py