#!/usr/bin/env bash

if [[ -v AKARI_TOKEN ]]; then
    echo "Akari_Token=${AKARI_TOKEN}" >> /Akari/Bot/.env
else
    echo "Missing Akari's bot token! AKARI_TOKEN environment variable is not set."
    exit 1;
fi

if [[ -v AKARI_DEV_TOKEN ]]; then
    echo "Akari_Dev_Token=${AKARI_DEV_TOKEN}" >> /Akari/Bot/.env
fi 

if [[ -v POSTGRES_USER ]]; then
    echo "Postgres_User=${POSTGRES_USER}" >> /Akari/Bot/.env
else
    echo "Missing Postgres_User env var! Postgres_User environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PASSWORD ]]; then
    echo "Postgres_Password=${POSTGRES_PASSWORD}" >> /Akari/Bot/.env
else
    echo "Missing Postgres_Password env var! Postgres_Password environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_HOST ]]; then
    echo "Postgres_Host=${POSTGRES_HOST}" >> /Akari/Bot/.env
else
    echo "Missing Postgres_Host env var! Postgres_Host environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PORT ]]; then
    echo "Postgres_Port=${POSTGRES_PORT}" >> /Akari/Bot/.env
else
    echo "Missing Postgres_Port env var! Postgres_Port environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_TAGS_DB ]]; then
    echo "Postgres_Tags_DB=${POSTGRES_TAGS_DB}" >> /Akari/Bot/.env
else
    echo "Missing Postgres_Tags_DB env var! Postgres_Tags_DB environment variable is not set."
    exit 1;
fi

AKARI_FIRST_START_CHECK="AKARI_FIRST_START"

if [ ! -f $AKARI_FIRST_START_CHECK ]; then
    touch $AKARI_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN AKARI USING DOCKER!' >> $AKARI_FIRST_START_CHECK
    python3 /Akari/seeder.py
fi

exec python3 /Akari/Bot/kumikobot.py