name: Docker Build (PostgreSQL)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    paths:
      - "Docker/pg/**"
    # branches:
    #   - dev
    # tags:
    #   - 'v*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/akari-pg
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.2.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-debian-pg-hub-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-debian-pg-hub-

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Docker/pg
          file: ./Docker/pg/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-debian-pg-hub

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-debian-pg-hub /tmp/.buildx-cache
