name: Lint

on:
  push:
    branches:
      - dev
    
  pull_request:
    branches:
      - dev
      - master

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

jobs: 
  Analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-v4-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry Dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          poetry install --with=dev
      
      - name: Run Pyright
        run: |
          make pyright
